apiVersion: v1
kind: ServiceAccount
metadata:
  name: reject-proxy 
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: reject-proxy 
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: reject-proxy 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reject-proxy
subjects:
- kind: ServiceAccount
  name: reject-proxy
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reject-proxy
data:
  neutron-lbaas: |
    method: POST
    url: https://someurl:443/v2.0/lbaas.*
    code: 403 # optional
    message: Go away! # optional
